title: rmqc0909
description: I've got your back!
author: rmqc0909
email: rmqc0909@163.com
github: rmqc0909

permalink: /blog/:year/:month/:title.html
markdown: kramdown
highlighter: pygments
highlight: true
safe: false
timezone: Asia/Shanghai
auto: false
encoding: utf-8
baseurl: ""
url: "https://rmqc0909.github.io"

paginate: 5
paginate_path: "page:num"
