auto: true

highlighter: 'pygments'
#paginate: 8
permalink: /:title

title:  rmqc0909's blog
url: https://rmqc0909.github.io
feed: /atom.xml
author_info: <a href="https://rmqc0909.github.io">rmqc0909</a>
