title: Map Maker
description: Keep Going
author: polokobe
email: fengtao_whu@163.com
github: polokobe

permalink: /blog/:year/:month/:title.html
markdown: kramdown
highlighter: pygments
highlight: true
safe: false
timezone: Asia/Shanghai
auto: false
encoding: utf-8
baseurl: ""
url: "x-carto.com"

paginate: 10
paginate_path: "page:num"
